name: 'Lint And Compile'

on: [push, pull_request, workflow_dispatch]

env:
  NODE_VERSION: '22'

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Generate Checker files
        run: npm run generate-code

      - name: Generate documentation files
        run: npm run generate-docs

      - name: Pretty and Eslint
        run: npm run lint:fix

      - name: Update Type-Coverage result
        run: npx type-coverage --detail true --update true

      - name: Ensure a clean working directory
        run: git diff --exit-code

      - name: Test Compile TypeScript
        run: npx tsc --noEmit

      - name: Test Run Project
        run: npm run test:run
